### ISSUE TITLE
Terima Kasih

### ISSUE THREAD

**Issue by azzamsa** [kholidfu/emacs_doc#1]
Assalamualaikum.

Saya ingin berterima kasih banyak atas karya akang ini. Sudah lama
sekali saya menghatamkannya. Kurang lebih pertengahan 2016
lalu. Teringat jelas saya membaca kegunaan \*scratch\* *buffer* (akang
gunakan untuk tempat anak akang mengetik sembari bermain dan
mengevaluasi lisp *expression*) di minggu awal saya mempelajari Emacs.

Tak terasa sudah lama saya bersama Emacs. Dari hari pertama saya
menghabiskan 2 jam lebih untuk tau apa itu *Meta key*, hingga hari ini
saya dapat melakukan banyak hal di dalamnya. Sungguh waktu yang tidak
sebentar.

Sudah lama saya melupakan keberadaan buku ini. Hingga akhirnya,
kemarin malam teman saya tidak sengaja menuliskan 'Emacs Indonesia'
pada kolom pencarian telegram. Kaget bahwa ternyata memang ada
(t.me/emacsID). Ia mengabarkannya kepada saya. Saya pun sontak
kaget. Saya pun melihat isi grup, beberapa *chat* di dalamnya
penasaran tentang sosok *sopier*. Ternyata karya akang sudah banyak
dibaca oleh teman-teman di Indonesia. Saya pun mencari kembali
blog-blog akang yang dulu saya baca dan mengirimkannya ke grup.

Sebenarnya saya tidak pernah menggunakan telegram untuk grup. Tetapi
mungkin saya akan coba. Mungkin saja saya bisa berbagi dengan
teman-teman.

Dari titik awal saya belajar, membaca buku akang hingga sekarang saya
ikut aktif kontribusi ke beberapa *upstream pacakge*. Sungguh saya
sangat bersyukur. Patut diakui bahwa buku akang memberikan banyak
pandangan bagi saya. Saya masih ingat membacanya dan meng-*highlight*
bagian-bagian yang penting.

Sekali lagi saya ingin mengucapkan terima kasih banyak atas karya
ini. Terima kasih yang tak terhingga. Hanya ini yang bisa saya
balaskan. Rasa terima kasih dan doa. Dahulu hanya akang yang saya
kenal sebagai pengguna Emacs di Indonesia. Meskipun saya belum pernah
menghubungi akang secara langsung. Sekali lagi terima kasih untuk
karyanya kang. Mungkin sebaiknya diletakkan di leanpub.

Semoga sehat dan sukses selalu kang Kholid.

-- Azzamsa

**Comment by kholidfu** [comment]
Wa'alaikumsalam mas Azzamsa...

Alhamdulillah kalau apa yang sedikit ini bisa memberi manfaat buat semua...

Sekali lagi terima kasih dan kalau memungkinkan tolong sampaikan salam ta'dzim saya buat semua...

**Comment by azzamsa** [comment]
> Alhamdulillah kalau apa yang sedikit ini bisa memberi manfaat buat semua...

Alhamdulillah :) 

> Sekali lagi terima kasih dan kalau memungkinkan tolong sampaikan salam ta'dzim saya buat semua...

Baik Kang. Akan saya sampaikan.
